// Force majeure clause printed at the foot of every fee announcement.

export const FORCE_MAJEURE = {
  en: [
    'In the event of force majeure occurrences, including but not limited to natural disasters such as storms, floods, earthquakes; global pandemics; fires, government mandates for academy closures, wars, strikes, riots, or any situations beyond the control of Palm River Academy, we will take all necessary measures to protect the health and safety of students and staff.',
    'Parents agree that in cases of force majeure, Palm River Academy reserves the right to temporarily close the center or transition to online learning. This is to ensure the continuity of the educational process in the safest possible conditions while maintaining the academy’s commitment to high educational standards.',
    'Furthermore, parents understand and accept that tuition and development fees already paid will not be refunded or reduced during the occurrence of force majeure events. These funds are essential for maintaining operational stability, retaining high-quality teaching staff on long-term contracts, and covering fixed salaries. By maintaining the agreed fees, Palm River Academy ensures that no additional required costs beyond the monthly tuition and development fees will be incurred during such periods.',
    'This clause does not apply to optional or third-party expenses, such as external examination fees (e.g., Cambridge Tests, GED) or off-campus activities, which are not included in the program fees and may still apply if the activity proceeds and parents choose to participate.',
    'Palm River Academy remains committed to using these funds efficiently to support ongoing educational delivery and protect the learning environment for all students.',
    'Palm River Academy is committed to promptly informing parents of any necessary changes related to teaching methods or other issues during force majeure occurrences. Communication will be conducted through email, and private group chat. The academy will also make every effort to minimize the negative impact on students\' learning experiences and ensure the continued delivery of quality education, whether through in-person or online platforms.',
    'The health and safety of students and staff will always be the top priority in such circumstances, and all decisions made will reflect this commitment.',
  ],
  vi: [
    'Trong trường hợp xảy ra bất khả kháng, bao gồm nhưng không giới hạn ở các thảm họa thiên nhiên như bão, lũ lụt, động đất; đại dịch toàn cầu; hỏa hoạn, lệnh của chính phủ về việc đóng cửa cơ sở giáo dục, chiến tranh, đình công, bạo loạn hoặc bất kỳ nguyên nhân nào nằm ngoài tầm kiểm soát của Palm River Academy, chúng tôi sẽ thực hiện mọi biện pháp cần thiết để bảo vệ sức khỏe và sự an toàn của học sinh và nhân viên.',
    'Phụ huynh đồng ý rằng trong trường hợp bất khả kháng, Palm River Academy có quyền tạm thời đóng cửa trung tâm hoặc chuyển sang học trực tuyến. Điều này nhằm đảm bảo tính liên tục của quá trình giáo dục trong điều kiện an toàn nhất có thể, đồng thời duy trì cam kết của trung tâm về các tiêu chuẩn giáo dục cao.',
    'Ngoài ra, phụ huynh hiểu và chấp nhận rằng học phí và phí phát triển cơ sở đã đóng sẽ không được hoàn trả hoặc giảm trong thời gian xảy ra các sự kiện bất khả kháng. Các khoản phí này là cần thiết để duy trì sự ổn định trong vận hành, giữ chân đội ngũ giáo viên chất lượng cao với các hợp đồng dài hạn, và chi trả các khoản lương cố định. Việc giữ nguyên các mức phí đã thỏa thuận giúp Palm River Academy đảm bảo rằng sẽ không phát sinh thêm bất kỳ chi phí nào ngoài học phí hàng tháng và phí phát triển cơ sở trong thời gian này.',
    'Điều khoản này không áp dụng cho các khoản chi tùy chọn hoặc từ bên thứ ba, chẳng hạn như lệ phí thi bên ngoài (ví dụ: kỳ thi Cambridge, GED) hoặc các hoạt động ngoài khuôn viên, vốn không bao gồm trong học phí chương trình và có thể vẫn được thu nếu hoạt động diễn ra và phụ huynh chọn tham gia.',
    'Palm River Academy vẫn cam kết sử dụng hiệu quả các khoản tiền này để hỗ trợ việc cung cấp giáo dục đang diễn ra và bảo vệ môi trường học tập cho tất cả học sinh.',
    'Palm River Academy cam kết thông báo kịp thời cho phụ huynh về bất kỳ thay đổi cần thiết nào liên quan đến phương pháp giảng dạy hoặc các vấn đề khác trong trường hợp bất khả kháng. Việc trao đổi sẽ được thực hiện qua email và trò chuyện nhóm riêng. Trung tâm cũng sẽ nỗ lực hết sức để giảm thiểu tác động tiêu cực đến trải nghiệm học tập của học sinh và đảm bảo tiếp tục cung cấp giáo dục chất lượng, dù là thông qua nền tảng trực tiếp hay trực tuyến.',
    'Sức khỏe và sự an toàn của học sinh và nhân viên sẽ luôn là ưu tiên hàng đầu trong những trường hợp như vậy và mọi quyết định đưa ra sẽ phản ánh cam kết này.',
  ],
}
